name: Actualizador ONPE ZenRows

on:
  schedule:
    - cron: '0 */2 * * *' # CORRE CADA 2 HORAS
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          ZENROWS_API_KEY: ${{ secrets.ZENROWS_API_KEY }}
        run: python main.py
      - name: Ejecutar Scraper API (api_to_sheets.py)
        env:
          ZENROWS_API_KEY: ${{ secrets.ZENROWS_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python api_to_sheets.py
