name: Actualizador ONPE a Sheets

on:
  schedule:
    # Corre cada hora (puedes cambiar este cron si lo quieres más o menos frecuente)
    - cron: '0 * * * *' 
  workflow_dispatch: # Permite ejecutarlo con un botón manualmente

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Ejecutar el script
        env:
          # Aquí inyectamos tu clave secreta de forma segura
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python main.py
